// Copyright (c) 2024
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package regions

import (
	"go.mau.fi/whatsmeow/proto/waCompanionReg"
	"go.mau.fi/whatsmeow/proto/waWa6"
	"go.mau.fi/whatsmeow/util/fingerprint"
)

func init() {
	config := &fingerprint.RegionConfig{
		Code: "IN",
		Name: "India",

		Languages: []fingerprint.LanguageConfig{
			{Code: "hi", Weight: 0.35, Countries: []string{"IN"}}, // 印地语 35%
			{Code: "ta", Weight: 0.15, Countries: []string{"IN"}}, // 泰米尔语 15%
			{Code: "te", Weight: 0.15, Countries: []string{"IN"}}, // 泰卢固语 15%
			{Code: "mr", Weight: 0.12, Countries: []string{"IN"}}, // 马拉地语 12%
			{Code: "bn", Weight: 0.13, Countries: []string{"IN"}}, // 孟加拉语 13%
			{Code: "kn", Weight: 0.10, Countries: []string{"IN"}}, // 卡纳达语 10%
		},

		DeviceDistribution: []fingerprint.PlatformDistribution{
			{
				Platform:     waWa6.ClientPayload_UserAgent_WEB,
				PlatformType: waCompanionReg.DeviceProps_CHROME,
				DeviceType:   waWa6.ClientPayload_UserAgent_DESKTOP,
				Weight:       0.70, // 70% Windows Web
				OSName:       "Windows",
				OSVersions:   []string{"10", "11"},
			},
			{
				Platform:     waWa6.ClientPayload_UserAgent_WEB,
				PlatformType: waCompanionReg.DeviceProps_CATALINA,
				DeviceType:   waWa6.ClientPayload_UserAgent_DESKTOP,
				Weight:       0.20, // 20% macOS
				OSName:       "macOS",
				OSVersions:   []string{"12", "13", "14"},
			},
			{
				Platform:     waWa6.ClientPayload_UserAgent_WEB,
				PlatformType: waCompanionReg.DeviceProps_DESKTOP,
				DeviceType:   waWa6.ClientPayload_UserAgent_DESKTOP,
				Weight:       0.10, // 10% Linux
				OSName:       "Linux",
				OSVersions:   []string{"5.15", "5.19", "6.1"},
			},
		},

		MobileNetworks: []fingerprint.MobileNetworkConfig{
			// MCC 404 (主要GSM网络)
			{MCC: "404", MNC: "01", OperatorName: "Vi (Vodafone Idea)", Weight: 0.20},
			{MCC: "404", MNC: "20", OperatorName: "Vodafone Idea", Weight: 0.15},
			{MCC: "404", MNC: "10", OperatorName: "Airtel", Weight: 0.10},
			{MCC: "404", MNC: "11", OperatorName: "BSNL", Weight: 0.10},
			{MCC: "404", MNC: "22", OperatorName: "Vodafone Idea", Weight: 0.03},
			{MCC: "404", MNC: "27", OperatorName: "Vodafone Idea", Weight: 0.02},
			{MCC: "404", MNC: "15", OperatorName: "BSNL", Weight: 0.02},
			{MCC: "404", MNC: "45", OperatorName: "Airtel", Weight: 0.01},
			// MCC 405 (CDMA/LTE网络) - Jio 的 LTE 网络配置（有效 MNC: 840, 854-874）
			{MCC: "405", MNC: "874", OperatorName: "Jio", Weight: 0.10},
			{MCC: "405", MNC: "865", OperatorName: "Jio", Weight: 0.02},
			{MCC: "405", MNC: "857", OperatorName: "Jio", Weight: 0.01},
		},

		DeviceModels: map[string][]fingerprint.DeviceModelConfig{
			"Apple": {
				// MacBook Pro 系列（印度市场主流，M1/M2/M3/M4芯片）
				{Model: "MacBook Pro 13 M1", ModelType: "MacBookPro17,1", Board: "Mac-"},
				{Model: "MacBook Pro 13 M2", ModelType: "MacBookPro18,3", Board: "Mac-"},
				{Model: "MacBook Pro 14 M1", ModelType: "MacBookPro18,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M1 Pro", ModelType: "MacBookPro18,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M1 Max", ModelType: "MacBookPro18,1", Board: "Mac-"},
				{Model: "MacBook Pro 16 M1", ModelType: "MacBookPro18,2", Board: "Mac-"},
				{Model: "MacBook Pro 16 M1 Pro", ModelType: "MacBookPro18,2", Board: "Mac-"},
				{Model: "MacBook Pro 16 M1 Max", ModelType: "MacBookPro18,2", Board: "Mac-"},
				{Model: "MacBook Pro 14 M2", ModelType: "MacBookPro19,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M2 Pro", ModelType: "MacBookPro19,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M2 Max", ModelType: "MacBookPro19,1", Board: "Mac-"},
				{Model: "MacBook Pro 16 M2", ModelType: "MacBookPro19,2", Board: "Mac-"},
				{Model: "MacBook Pro 16 M2 Pro", ModelType: "MacBookPro19,2", Board: "Mac-"},
				{Model: "MacBook Pro 16 M2 Max", ModelType: "MacBookPro19,2", Board: "Mac-"},
				{Model: "MacBook Pro 14 M3", ModelType: "MacBookPro20,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M3 Pro", ModelType: "MacBookPro20,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M3 Max", ModelType: "MacBookPro20,1", Board: "Mac-"},
				{Model: "MacBook Pro 16 M3", ModelType: "MacBookPro20,2", Board: "Mac-"},
				{Model: "MacBook Pro 16 M3 Pro", ModelType: "MacBookPro20,2", Board: "Mac-"},
				{Model: "MacBook Pro 16 M3 Max", ModelType: "MacBookPro20,2", Board: "Mac-"},
				{Model: "MacBook Pro 14 M4", ModelType: "Mac16,1", Board: "Mac-"},
				{Model: "MacBook Pro 14 M4 Pro", ModelType: "Mac16,8", Board: "Mac-"},
				{Model: "MacBook Pro 16 M4 Max", ModelType: "Mac16,5", Board: "Mac-"},
				// MacBook Air 系列
				{Model: "MacBook Air M1", ModelType: "MacBookAir10,1", Board: "Mac-"},
				{Model: "MacBook Air M2", ModelType: "MacBookAir14,1", Board: "Mac-"},
				{Model: "MacBook Air M2 13", ModelType: "MacBookAir14,1", Board: "Mac-"},
				{Model: "MacBook Air M2 15", ModelType: "MacBookAir15,2", Board: "Mac-"},
				{Model: "MacBook Air M3", ModelType: "MacBookAir15,1", Board: "Mac-"},
				{Model: "MacBook Air M3 13", ModelType: "MacBookAir15,1", Board: "Mac-"},
				{Model: "MacBook Air M3 15", ModelType: "MacBookAir15,2", Board: "Mac-"},
				// iMac 系列
				{Model: "iMac 24 M1", ModelType: "iMac21,1", Board: "Mac-"},
				{Model: "iMac 24 M1 7-core", ModelType: "iMac21,1", Board: "Mac-"},
				{Model: "iMac 24 M1 8-core", ModelType: "iMac21,1", Board: "Mac-"},
				{Model: "iMac 24 M3", ModelType: "Mac15,4", Board: "Mac-"},
				{Model: "iMac 24 M3 8-core", ModelType: "Mac15,4", Board: "Mac-"},
				{Model: "iMac 24 M3 10-core", ModelType: "Mac15,5", Board: "Mac-"},
				// Mac mini 系列
				{Model: "Mac mini M1", ModelType: "Macmini9,1", Board: "Mac-"},
				{Model: "Mac mini M2", ModelType: "Macmini14,1", Board: "Mac-"},
				{Model: "Mac mini M2 Pro", ModelType: "Macmini14,2", Board: "Mac-"},
				{Model: "Mac Studio M1 Max", ModelType: "Mac13,1", Board: "Mac-"},
				{Model: "Mac Studio M1 Ultra", ModelType: "Mac13,2", Board: "Mac-"},
				{Model: "Mac Studio M2 Max", ModelType: "Mac14,13", Board: "Mac-"},
				{Model: "Mac Studio M2 Ultra", ModelType: "Mac14,14", Board: "Mac-"},
			},
			"Microsoft": {
				// Surface Pro 系列（印度市场）
				{Model: "Surface Pro 7", ModelType: "SurfacePro7", Board: "Surface"},
				{Model: "Surface Pro 7+", ModelType: "SurfacePro7Plus", Board: "Surface"},
				{Model: "Surface Pro 8", ModelType: "SurfacePro8", Board: "Surface"},
				{Model: "Surface Pro 9", ModelType: "SurfacePro9", Board: "Surface"},
				{Model: "Surface Pro 9 5G", ModelType: "SurfacePro95G", Board: "Surface"},
				{Model: "Surface Pro 10", ModelType: "SurfacePro10", Board: "Surface"},
				{Model: "Surface Pro 10 Business", ModelType: "SurfacePro10Biz", Board: "Surface"},
				// Surface Laptop 系列
				{Model: "Surface Laptop 3", ModelType: "SurfaceLaptop3", Board: "Surface"},
				{Model: "Surface Laptop 4", ModelType: "SurfaceLaptop4", Board: "Surface"},
				{Model: "Surface Laptop 5", ModelType: "SurfaceLaptop5", Board: "Surface"},
				{Model: "Surface Laptop 6", ModelType: "SurfaceLaptop6", Board: "Surface"},
				{Model: "Surface Laptop Studio", ModelType: "SurfaceLaptopStudio", Board: "Surface"},
				{Model: "Surface Laptop Studio 2", ModelType: "SurfaceLaptopStudio2", Board: "Surface"},
				{Model: "Surface Laptop Go", ModelType: "SurfaceLaptopGo", Board: "Surface"},
				{Model: "Surface Laptop Go 2", ModelType: "SurfaceLaptopGo2", Board: "Surface"},
				{Model: "Surface Laptop Go 3", ModelType: "SurfaceLaptopGo3", Board: "Surface"},
				// Surface Book 系列
				{Model: "Surface Book 2", ModelType: "SurfaceBook2", Board: "Surface"},
				{Model: "Surface Book 3", ModelType: "SurfaceBook3", Board: "Surface"},
				// Surface Go 系列
				{Model: "Surface Go", ModelType: "SurfaceGo", Board: "Surface"},
				{Model: "Surface Go 2", ModelType: "SurfaceGo2", Board: "Surface"},
				{Model: "Surface Go 3", ModelType: "SurfaceGo3", Board: "Surface"},
				{Model: "Surface Go 4", ModelType: "SurfaceGo4", Board: "Surface"},
				// Surface Studio 系列
				{Model: "Surface Studio 2", ModelType: "SurfaceStudio2", Board: "Surface"},
				{Model: "Surface Studio 2+", ModelType: "SurfaceStudio2Plus", Board: "Surface"},
			},
			"Dell": {
				// XPS 系列（印度市场主流）
				{Model: "XPS 13 9300", ModelType: "XPS139300", Board: "Dell"},
				{Model: "XPS 13 9310", ModelType: "XPS139310", Board: "Dell"},
				{Model: "XPS 13 9320", ModelType: "XPS139320", Board: "Dell"},
				{Model: "XPS 13 9330", ModelType: "XPS139330", Board: "Dell"},
				{Model: "XPS 13 9340", ModelType: "XPS139340", Board: "Dell"},
				{Model: "XPS 13 Plus 9320", ModelType: "XPS139320", Board: "Dell"},
				{Model: "XPS 15 9500", ModelType: "XPS159500", Board: "Dell"},
				{Model: "XPS 15 9510", ModelType: "XPS159510", Board: "Dell"},
				{Model: "XPS 15 9520", ModelType: "XPS159520", Board: "Dell"},
				{Model: "XPS 15 9530", ModelType: "XPS159530", Board: "Dell"},
				{Model: "XPS 15 9540", ModelType: "XPS159540", Board: "Dell"},
				{Model: "XPS 17 9700", ModelType: "XPS179700", Board: "Dell"},
				{Model: "XPS 17 9710", ModelType: "XPS179710", Board: "Dell"},
				{Model: "XPS 17 9720", ModelType: "XPS179720", Board: "Dell"},
				{Model: "XPS 17 9730", ModelType: "XPS179730", Board: "Dell"},
				// Inspiron 系列（中端，印度市场常见）
				{Model: "Inspiron 14 3000", ModelType: "Inspiron143000", Board: "Dell"},
				{Model: "Inspiron 14 3420", ModelType: "Inspiron143420", Board: "Dell"},
				{Model: "Inspiron 14 3520", ModelType: "Inspiron143520", Board: "Dell"},
				{Model: "Inspiron 14 5000", ModelType: "Inspiron145000", Board: "Dell"},
				{Model: "Inspiron 14 5410", ModelType: "Inspiron145410", Board: "Dell"},
				{Model: "Inspiron 14 5415", ModelType: "Inspiron145415", Board: "Dell"},
				{Model: "Inspiron 14 5420", ModelType: "Inspiron145420", Board: "Dell"},
				{Model: "Inspiron 14 5425", ModelType: "Inspiron145425", Board: "Dell"},
				{Model: "Inspiron 15 3000", ModelType: "Inspiron153000", Board: "Dell"},
				{Model: "Inspiron 15 3520", ModelType: "Inspiron153520", Board: "Dell"},
				{Model: "Inspiron 15 3525", ModelType: "Inspiron153525", Board: "Dell"},
				{Model: "Inspiron 15 5000", ModelType: "Inspiron155000", Board: "Dell"},
				{Model: "Inspiron 15 5510", ModelType: "Inspiron155510", Board: "Dell"},
				{Model: "Inspiron 15 5515", ModelType: "Inspiron155515", Board: "Dell"},
				{Model: "Inspiron 15 5520", ModelType: "Inspiron155520", Board: "Dell"},
				{Model: "Inspiron 15 5525", ModelType: "Inspiron155525", Board: "Dell"},
				{Model: "Inspiron 16 Plus", ModelType: "Inspiron16Plus", Board: "Dell"},
				{Model: "Inspiron 16 Plus 7620", ModelType: "Inspiron167620", Board: "Dell"},
				{Model: "Inspiron 14 2-in-1 7415", ModelType: "Inspiron147415", Board: "Dell"},
				{Model: "Inspiron 14 2-in-1 7420", ModelType: "Inspiron147420", Board: "Dell"},
				{Model: "Inspiron 15 2-in-1 7520", ModelType: "Inspiron157520", Board: "Dell"},
				// Latitude 系列（商务，印度市场常见）
				{Model: "Latitude 3420", ModelType: "Latitude3420", Board: "Dell"},
				{Model: "Latitude 3520", ModelType: "Latitude3520", Board: "Dell"},
				{Model: "Latitude 5430", ModelType: "Latitude5430", Board: "Dell"},
				{Model: "Latitude 5431", ModelType: "Latitude5431", Board: "Dell"},
				{Model: "Latitude 5440", ModelType: "Latitude5440", Board: "Dell"},
				{Model: "Latitude 5530", ModelType: "Latitude5530", Board: "Dell"},
				{Model: "Latitude 5531", ModelType: "Latitude5531", Board: "Dell"},
				{Model: "Latitude 5540", ModelType: "Latitude5540", Board: "Dell"},
				{Model: "Latitude 7420", ModelType: "Latitude7420", Board: "Dell"},
				{Model: "Latitude 7430", ModelType: "Latitude7430", Board: "Dell"},
				{Model: "Latitude 7440", ModelType: "Latitude7440", Board: "Dell"},
				{Model: "Latitude 7520", ModelType: "Latitude7520", Board: "Dell"},
				{Model: "Latitude 7530", ModelType: "Latitude7530", Board: "Dell"},
				{Model: "Latitude 7540", ModelType: "Latitude7540", Board: "Dell"},
				// Vostro 系列（中小企业）
				{Model: "Vostro 14 3000", ModelType: "Vostro143000", Board: "Dell"},
				{Model: "Vostro 14 3420", ModelType: "Vostro143420", Board: "Dell"},
				{Model: "Vostro 14 3520", ModelType: "Vostro143520", Board: "Dell"},
				{Model: "Vostro 15 3000", ModelType: "Vostro153000", Board: "Dell"},
				{Model: "Vostro 15 3520", ModelType: "Vostro153520", Board: "Dell"},
				{Model: "Vostro 14 5000", ModelType: "Vostro145000", Board: "Dell"},
				{Model: "Vostro 14 5410", ModelType: "Vostro145410", Board: "Dell"},
				{Model: "Vostro 14 5420", ModelType: "Vostro145420", Board: "Dell"},
				{Model: "Vostro 15 5000", ModelType: "Vostro155000", Board: "Dell"},
				{Model: "Vostro 15 5510", ModelType: "Vostro155510", Board: "Dell"},
				{Model: "Vostro 15 5520", ModelType: "Vostro155520", Board: "Dell"},
				// Precision 系列（工作站）
				{Model: "Precision 3560", ModelType: "Precision3560", Board: "Dell"},
				{Model: "Precision 3561", ModelType: "Precision3561", Board: "Dell"},
				{Model: "Precision 5470", ModelType: "Precision5470", Board: "Dell"},
				{Model: "Precision 5570", ModelType: "Precision5570", Board: "Dell"},
				{Model: "Precision 7670", ModelType: "Precision7670", Board: "Dell"},
				{Model: "Precision 7770", ModelType: "Precision7770", Board: "Dell"},
			},
			"HP": {
				// Spectre 系列（高端，印度市场）
				{Model: "Spectre x360 13", ModelType: "Spectre13", Board: "HP"},
				{Model: "Spectre x360 13.5", ModelType: "Spectre13.5", Board: "HP"},
				{Model: "Spectre x360 14", ModelType: "Spectre14", Board: "HP"},
				{Model: "Spectre x360 15", ModelType: "Spectre15", Board: "HP"},
				{Model: "Spectre x360 16", ModelType: "Spectre16", Board: "HP"},
				{Model: "Spectre 13", ModelType: "Spectre13", Board: "HP"},
				{Model: "Spectre 14", ModelType: "Spectre14", Board: "HP"},
				{Model: "Spectre 15", ModelType: "Spectre15", Board: "HP"},
				// Envy 系列（中高端）
				{Model: "Envy x360 13", ModelType: "Envy13", Board: "HP"},
				{Model: "Envy x360 13.3", ModelType: "Envy13.3", Board: "HP"},
				{Model: "Envy x360 15", ModelType: "Envy15", Board: "HP"},
				{Model: "Envy x360 15.6", ModelType: "Envy15.6", Board: "HP"},
				{Model: "Envy 13", ModelType: "Envy13", Board: "HP"},
				{Model: "Envy 13.3", ModelType: "Envy13.3", Board: "HP"},
				{Model: "Envy 15", ModelType: "Envy15", Board: "HP"},
				{Model: "Envy 15.6", ModelType: "Envy15.6", Board: "HP"},
				{Model: "Envy 16", ModelType: "Envy16", Board: "HP"},
				{Model: "Envy 17", ModelType: "Envy17", Board: "HP"},
				// Pavilion 系列（中端，印度市场常见）
				{Model: "Pavilion 14", ModelType: "Pavilion14", Board: "HP"},
				{Model: "Pavilion 14-ce", ModelType: "Pavilion14ce", Board: "HP"},
				{Model: "Pavilion 14-dv", ModelType: "Pavilion14dv", Board: "HP"},
				{Model: "Pavilion 15", ModelType: "Pavilion15", Board: "HP"},
				{Model: "Pavilion 15-ce", ModelType: "Pavilion15ce", Board: "HP"},
				{Model: "Pavilion 15-dv", ModelType: "Pavilion15dv", Board: "HP"},
				{Model: "Pavilion Plus 14", ModelType: "PavilionPlus14", Board: "HP"},
				{Model: "Pavilion Plus 15", ModelType: "PavilionPlus15", Board: "HP"},
				{Model: "Pavilion x360 14", ModelType: "Pavilionx36014", Board: "HP"},
				{Model: "Pavilion x360 15", ModelType: "Pavilionx36015", Board: "HP"},
				{Model: "Pavilion Gaming 15", ModelType: "PavilionGaming15", Board: "HP"},
				{Model: "Pavilion Gaming 16", ModelType: "PavilionGaming16", Board: "HP"},
				// EliteBook 系列（商务）
				{Model: "EliteBook 840 G7", ModelType: "EliteBook840G7", Board: "HP"},
				{Model: "EliteBook 840 G8", ModelType: "EliteBook840G8", Board: "HP"},
				{Model: "EliteBook 840 G9", ModelType: "EliteBook840G9", Board: "HP"},
				{Model: "EliteBook 840 G10", ModelType: "EliteBook840G10", Board: "HP"},
				{Model: "EliteBook 840 G11", ModelType: "EliteBook840G11", Board: "HP"},
				{Model: "EliteBook 850 G7", ModelType: "EliteBook850G7", Board: "HP"},
				{Model: "EliteBook 850 G8", ModelType: "EliteBook850G8", Board: "HP"},
				{Model: "EliteBook 850 G9", ModelType: "EliteBook850G9", Board: "HP"},
				{Model: "EliteBook 850 G10", ModelType: "EliteBook850G10", Board: "HP"},
				{Model: "EliteBook 850 G11", ModelType: "EliteBook850G11", Board: "HP"},
				{Model: "EliteBook 860 G9", ModelType: "EliteBook860G9", Board: "HP"},
				{Model: "EliteBook 860 G10", ModelType: "EliteBook860G10", Board: "HP"},
				{Model: "EliteBook 1040 G9", ModelType: "EliteBook1040G9", Board: "HP"},
				{Model: "EliteBook 1040 G10", ModelType: "EliteBook1040G10", Board: "HP"},
				// ProBook 系列（商务）
				{Model: "ProBook 440 G8", ModelType: "ProBook440G8", Board: "HP"},
				{Model: "ProBook 440 G9", ModelType: "ProBook440G9", Board: "HP"},
				{Model: "ProBook 450 G8", ModelType: "ProBook450G8", Board: "HP"},
				{Model: "ProBook 450 G9", ModelType: "ProBook450G9", Board: "HP"},
				// OMEN 系列（游戏）
				{Model: "OMEN 15", ModelType: "OMEN15", Board: "HP"},
				{Model: "OMEN 16", ModelType: "OMEN16", Board: "HP"},
				{Model: "OMEN 17", ModelType: "OMEN17", Board: "HP"},
				{Model: "OMEN Transcend 14", ModelType: "OMENTranscend14", Board: "HP"},
				{Model: "OMEN Transcend 16", ModelType: "OMENTranscend16", Board: "HP"},
			},
			"Lenovo": {
				// ThinkPad 系列（商务，印度市场主流）
				{Model: "ThinkPad X1 Carbon Gen 8", ModelType: "ThinkPadX1CarbonG8", Board: "Lenovo"},
				{Model: "ThinkPad X1 Carbon Gen 9", ModelType: "ThinkPadX1CarbonG9", Board: "Lenovo"},
				{Model: "ThinkPad X1 Carbon Gen 10", ModelType: "ThinkPadX1CarbonG10", Board: "Lenovo"},
				{Model: "ThinkPad X1 Carbon Gen 11", ModelType: "ThinkPadX1CarbonG11", Board: "Lenovo"},
				{Model: "ThinkPad X1 Carbon Gen 12", ModelType: "ThinkPadX1CarbonG12", Board: "Lenovo"},
				{Model: "ThinkPad X1 Nano Gen 1", ModelType: "ThinkPadX1NanoG1", Board: "Lenovo"},
				{Model: "ThinkPad X1 Nano Gen 2", ModelType: "ThinkPadX1NanoG2", Board: "Lenovo"},
				{Model: "ThinkPad X1 Extreme Gen 4", ModelType: "ThinkPadX1ExtremeG4", Board: "Lenovo"},
				{Model: "ThinkPad X1 Extreme Gen 5", ModelType: "ThinkPadX1ExtremeG5", Board: "Lenovo"},
				{Model: "ThinkPad T14 Gen 1", ModelType: "ThinkPadT14G1", Board: "Lenovo"},
				{Model: "ThinkPad T14 Gen 2", ModelType: "ThinkPadT14G2", Board: "Lenovo"},
				{Model: "ThinkPad T14 Gen 3", ModelType: "ThinkPadT14G3", Board: "Lenovo"},
				{Model: "ThinkPad T14 Gen 4", ModelType: "ThinkPadT14G4", Board: "Lenovo"},
				{Model: "ThinkPad T14 Gen 5", ModelType: "ThinkPadT14G5", Board: "Lenovo"},
				{Model: "ThinkPad T15 Gen 2", ModelType: "ThinkPadT15G2", Board: "Lenovo"},
				{Model: "ThinkPad T15 Gen 3", ModelType: "ThinkPadT15G3", Board: "Lenovo"},
				{Model: "ThinkPad T16 Gen 1", ModelType: "ThinkPadT16G1", Board: "Lenovo"},
				{Model: "ThinkPad T16 Gen 2", ModelType: "ThinkPadT16G2", Board: "Lenovo"},
				{Model: "ThinkPad T16 Gen 3", ModelType: "ThinkPadT16G3", Board: "Lenovo"},
				{Model: "ThinkPad E14 Gen 1", ModelType: "ThinkPadE14G1", Board: "Lenovo"},
				{Model: "ThinkPad E14 Gen 2", ModelType: "ThinkPadE14G2", Board: "Lenovo"},
				{Model: "ThinkPad E14 Gen 3", ModelType: "ThinkPadE14G3", Board: "Lenovo"},
				{Model: "ThinkPad E14 Gen 4", ModelType: "ThinkPadE14G4", Board: "Lenovo"},
				{Model: "ThinkPad E14 Gen 5", ModelType: "ThinkPadE14G5", Board: "Lenovo"},
				{Model: "ThinkPad E15 Gen 1", ModelType: "ThinkPadE15G1", Board: "Lenovo"},
				{Model: "ThinkPad E15 Gen 2", ModelType: "ThinkPadE15G2", Board: "Lenovo"},
				{Model: "ThinkPad E15 Gen 3", ModelType: "ThinkPadE15G3", Board: "Lenovo"},
				{Model: "ThinkPad E15 Gen 4", ModelType: "ThinkPadE15G4", Board: "Lenovo"},
				{Model: "ThinkPad E16 Gen 1", ModelType: "ThinkPadE16G1", Board: "Lenovo"},
				{Model: "ThinkPad L14 Gen 1", ModelType: "ThinkPadL14G1", Board: "Lenovo"},
				{Model: "ThinkPad L14 Gen 2", ModelType: "ThinkPadL14G2", Board: "Lenovo"},
				{Model: "ThinkPad L14 Gen 3", ModelType: "ThinkPadL14G3", Board: "Lenovo"},
				{Model: "ThinkPad L15 Gen 1", ModelType: "ThinkPadL15G1", Board: "Lenovo"},
				{Model: "ThinkPad L15 Gen 2", ModelType: "ThinkPadL15G2", Board: "Lenovo"},
				{Model: "ThinkPad L15 Gen 3", ModelType: "ThinkPadL15G3", Board: "Lenovo"},
				{Model: "ThinkPad P14s Gen 1", ModelType: "ThinkPadP14sG1", Board: "Lenovo"},
				{Model: "ThinkPad P14s Gen 2", ModelType: "ThinkPadP14sG2", Board: "Lenovo"},
				{Model: "ThinkPad P14s Gen 3", ModelType: "ThinkPadP14sG3", Board: "Lenovo"},
				{Model: "ThinkPad P14s Gen 4", ModelType: "ThinkPadP14sG4", Board: "Lenovo"},
				{Model: "ThinkPad P16s Gen 1", ModelType: "ThinkPadP16sG1", Board: "Lenovo"},
				{Model: "ThinkPad P16s Gen 2", ModelType: "ThinkPadP16sG2", Board: "Lenovo"},
				{Model: "ThinkPad X1 Yoga Gen 6", ModelType: "ThinkPadX1YogaG6", Board: "Lenovo"},
				{Model: "ThinkPad X1 Yoga Gen 7", ModelType: "ThinkPadX1YogaG7", Board: "Lenovo"},
				{Model: "ThinkPad X1 Yoga Gen 8", ModelType: "ThinkPadX1YogaG8", Board: "Lenovo"},
				{Model: "ThinkPad X1 Yoga Gen 9", ModelType: "ThinkPadX1YogaG9", Board: "Lenovo"},
				// IdeaPad 系列（消费级，印度市场常见）
				{Model: "IdeaPad 3", ModelType: "IdeaPad3", Board: "Lenovo"},
				{Model: "IdeaPad 3 14", ModelType: "IdeaPad314", Board: "Lenovo"},
				{Model: "IdeaPad 3 15", ModelType: "IdeaPad315", Board: "Lenovo"},
				{Model: "IdeaPad 3 17", ModelType: "IdeaPad317", Board: "Lenovo"},
				{Model: "IdeaPad 5", ModelType: "IdeaPad5", Board: "Lenovo"},
				{Model: "IdeaPad 5 14", ModelType: "IdeaPad514", Board: "Lenovo"},
				{Model: "IdeaPad 5 15", ModelType: "IdeaPad515", Board: "Lenovo"},
				{Model: "IdeaPad Flex 5", ModelType: "IdeaPadFlex5", Board: "Lenovo"},
				{Model: "IdeaPad Flex 5 14", ModelType: "IdeaPadFlex514", Board: "Lenovo"},
				{Model: "IdeaPad Flex 5 15", ModelType: "IdeaPadFlex515", Board: "Lenovo"},
				{Model: "IdeaPad Slim 3", ModelType: "IdeaPadSlim3", Board: "Lenovo"},
				{Model: "IdeaPad Slim 3 14", ModelType: "IdeaPadSlim314", Board: "Lenovo"},
				{Model: "IdeaPad Slim 3 15", ModelType: "IdeaPadSlim315", Board: "Lenovo"},
				{Model: "IdeaPad Slim 5", ModelType: "IdeaPadSlim5", Board: "Lenovo"},
				{Model: "IdeaPad Slim 5 14", ModelType: "IdeaPadSlim514", Board: "Lenovo"},
				{Model: "IdeaPad Slim 5 15", ModelType: "IdeaPadSlim515", Board: "Lenovo"},
				{Model: "IdeaPad Gaming 3", ModelType: "IdeaPadGaming3", Board: "Lenovo"},
				{Model: "IdeaPad Gaming 3 15", ModelType: "IdeaPadGaming315", Board: "Lenovo"},
				{Model: "IdeaPad Gaming 3 16", ModelType: "IdeaPadGaming316", Board: "Lenovo"},
				{Model: "IdeaPad Gaming 5", ModelType: "IdeaPadGaming5", Board: "Lenovo"},
				{Model: "IdeaPad Gaming 5 15", ModelType: "IdeaPadGaming515", Board: "Lenovo"},
				{Model: "IdeaPad Gaming 5 16", ModelType: "IdeaPadGaming516", Board: "Lenovo"},
				// Yoga 系列（2-in-1）
				{Model: "Yoga 6", ModelType: "Yoga6", Board: "Lenovo"},
				{Model: "Yoga 7i", ModelType: "Yoga7i", Board: "Lenovo"},
				{Model: "Yoga 7i 14", ModelType: "Yoga7i14", Board: "Lenovo"},
				{Model: "Yoga 7i 15", ModelType: "Yoga7i15", Board: "Lenovo"},
				{Model: "Yoga 9i", ModelType: "Yoga9i", Board: "Lenovo"},
				{Model: "Yoga 9i 14", ModelType: "Yoga9i14", Board: "Lenovo"},
				{Model: "Yoga 9i 15", ModelType: "Yoga9i15", Board: "Lenovo"},
				{Model: "Yoga Slim 7", ModelType: "YogaSlim7", Board: "Lenovo"},
				{Model: "Yoga Slim 7 14", ModelType: "YogaSlim714", Board: "Lenovo"},
				{Model: "Yoga Slim 7 15", ModelType: "YogaSlim715", Board: "Lenovo"},
				{Model: "Yoga Slim 7 Pro", ModelType: "YogaSlim7Pro", Board: "Lenovo"},
				{Model: "Yoga Slim 7 Pro 14", ModelType: "YogaSlim7Pro14", Board: "Lenovo"},
				{Model: "Yoga Slim 7 Pro 16", ModelType: "YogaSlim7Pro16", Board: "Lenovo"},
				{Model: "Yoga Slim 9i", ModelType: "YogaSlim9i", Board: "Lenovo"},
				// Legion 系列（游戏）
				{Model: "Legion 5", ModelType: "Legion5", Board: "Lenovo"},
				{Model: "Legion 5 15", ModelType: "Legion515", Board: "Lenovo"},
				{Model: "Legion 5 17", ModelType: "Legion517", Board: "Lenovo"},
				{Model: "Legion 5 Pro", ModelType: "Legion5Pro", Board: "Lenovo"},
				{Model: "Legion 5 Pro 16", ModelType: "Legion5Pro16", Board: "Lenovo"},
				{Model: "Legion 7", ModelType: "Legion7", Board: "Lenovo"},
				{Model: "Legion 7 16", ModelType: "Legion716", Board: "Lenovo"},
				{Model: "Legion Slim 5", ModelType: "LegionSlim5", Board: "Lenovo"},
				{Model: "Legion Slim 7", ModelType: "LegionSlim7", Board: "Lenovo"},
			},
			"Acer": {
				// Aspire 系列（中低端，印度市场主流）
				{Model: "Aspire 3", ModelType: "Aspire3", Board: "Acer"},
				{Model: "Aspire 3 A315", ModelType: "Aspire3A315", Board: "Acer"},
				{Model: "Aspire 3 A315-58", ModelType: "Aspire3A31558", Board: "Acer"},
				{Model: "Aspire 3 A315-59", ModelType: "Aspire3A31559", Board: "Acer"},
				{Model: "Aspire 3 A317", ModelType: "Aspire3A317", Board: "Acer"},
				{Model: "Aspire 5", ModelType: "Aspire5", Board: "Acer"},
				{Model: "Aspire 5 A515", ModelType: "Aspire5A515", Board: "Acer"},
				{Model: "Aspire 5 A515-56", ModelType: "Aspire5A51556", Board: "Acer"},
				{Model: "Aspire 5 A515-57", ModelType: "Aspire5A51557", Board: "Acer"},
				{Model: "Aspire 5 A515-58", ModelType: "Aspire5A51558", Board: "Acer"},
				{Model: "Aspire 5 A517", ModelType: "Aspire5A517", Board: "Acer"},
				{Model: "Aspire 7", ModelType: "Aspire7", Board: "Acer"},
				{Model: "Aspire 7 A715", ModelType: "Aspire7A715", Board: "Acer"},
				{Model: "Aspire 7 A717", ModelType: "Aspire7A717", Board: "Acer"},
				// Swift 系列（轻薄）
				{Model: "Swift 3", ModelType: "Swift3", Board: "Acer"},
				{Model: "Swift 3 SF314", ModelType: "Swift3SF314", Board: "Acer"},
				{Model: "Swift 3 SF315", ModelType: "Swift3SF315", Board: "Acer"},
				{Model: "Swift 5", ModelType: "Swift5", Board: "Acer"},
				{Model: "Swift 5 SF514", ModelType: "Swift5SF514", Board: "Acer"},
				{Model: "Swift 5 SF515", ModelType: "Swift5SF515", Board: "Acer"},
				{Model: "Swift X", ModelType: "SwiftX", Board: "Acer"},
				{Model: "Swift X SFX14", ModelType: "SwiftXSFX14", Board: "Acer"},
				{Model: "Swift X SFX16", ModelType: "SwiftXSFX16", Board: "Acer"},
				{Model: "Swift Go 14", ModelType: "SwiftGo14", Board: "Acer"},
				{Model: "Swift Go 14 SFG14", ModelType: "SwiftGo14SFG14", Board: "Acer"},
				{Model: "Swift Go 16", ModelType: "SwiftGo16", Board: "Acer"},
				{Model: "Swift Go 16 SFG16", ModelType: "SwiftGo16SFG16", Board: "Acer"},
				// Predator 系列（游戏）
				{Model: "Predator Helios 300", ModelType: "PredatorHelios300", Board: "Acer"},
				{Model: "Predator Helios 300 PH315", ModelType: "PredatorHelios300PH315", Board: "Acer"},
				{Model: "Predator Helios 300 PH317", ModelType: "PredatorHelios300PH317", Board: "Acer"},
				{Model: "Predator Helios 16", ModelType: "PredatorHelios16", Board: "Acer"},
				{Model: "Predator Helios 16 PH16", ModelType: "PredatorHelios16PH16", Board: "Acer"},
				{Model: "Predator Helios 18", ModelType: "PredatorHelios18", Board: "Acer"},
				{Model: "Predator Triton 300", ModelType: "PredatorTriton300", Board: "Acer"},
				{Model: "Predator Triton 300 PT315", ModelType: "PredatorTriton300PT315", Board: "Acer"},
				{Model: "Predator Triton 500", ModelType: "PredatorTriton500", Board: "Acer"},
				{Model: "Predator Triton 500 SE", ModelType: "PredatorTriton500SE", Board: "Acer"},
				// Nitro 系列（游戏）
				{Model: "Nitro 5", ModelType: "Nitro5", Board: "Acer"},
				{Model: "Nitro 5 AN515", ModelType: "Nitro5AN515", Board: "Acer"},
				{Model: "Nitro 5 AN517", ModelType: "Nitro5AN517", Board: "Acer"},
				{Model: "Nitro 16", ModelType: "Nitro16", Board: "Acer"},
				{Model: "Nitro 17", ModelType: "Nitro17", Board: "Acer"},
				{Model: "Nitro 7", ModelType: "Nitro7", Board: "Acer"},
				// TravelMate 系列（商务）
				{Model: "TravelMate P2", ModelType: "TravelMateP2", Board: "Acer"},
				{Model: "TravelMate P4", ModelType: "TravelMateP4", Board: "Acer"},
				{Model: "TravelMate Spin P4", ModelType: "TravelMateSpinP4", Board: "Acer"},
			},
			"ASUS": {
				// ZenBook 系列（高端）
				{Model: "ZenBook 13", ModelType: "ZenBook13", Board: "ASUS"},
				{Model: "ZenBook 13 UX325", ModelType: "ZenBook13UX325", Board: "ASUS"},
				{Model: "ZenBook 13 UX333", ModelType: "ZenBook13UX333", Board: "ASUS"},
				{Model: "ZenBook 14", ModelType: "ZenBook14", Board: "ASUS"},
				{Model: "ZenBook 14 UX425", ModelType: "ZenBook14UX425", Board: "ASUS"},
				{Model: "ZenBook 14 UX434", ModelType: "ZenBook14UX434", Board: "ASUS"},
				{Model: "ZenBook 15", ModelType: "ZenBook15", Board: "ASUS"},
				{Model: "ZenBook 15 UX535", ModelType: "ZenBook15UX535", Board: "ASUS"},
				{Model: "ZenBook S13", ModelType: "ZenBookS13", Board: "ASUS"},
				{Model: "ZenBook S13 UX393", ModelType: "ZenBookS13UX393", Board: "ASUS"},
				{Model: "ZenBook Pro 14", ModelType: "ZenBookPro14", Board: "ASUS"},
				{Model: "ZenBook Pro 15", ModelType: "ZenBookPro15", Board: "ASUS"},
				{Model: "ZenBook Pro 16X", ModelType: "ZenBookPro16X", Board: "ASUS"},
				// VivoBook 系列（中端，印度市场常见）
				{Model: "VivoBook 14", ModelType: "VivoBook14", Board: "ASUS"},
				{Model: "VivoBook 14 X415", ModelType: "VivoBook14X415", Board: "ASUS"},
				{Model: "VivoBook 14 X421", ModelType: "VivoBook14X421", Board: "ASUS"},
				{Model: "VivoBook 15", ModelType: "VivoBook15", Board: "ASUS"},
				{Model: "VivoBook 15 X515", ModelType: "VivoBook15X515", Board: "ASUS"},
				{Model: "VivoBook S14", ModelType: "VivoBookS14", Board: "ASUS"},
				{Model: "VivoBook S14 X413", ModelType: "VivoBookS14X413", Board: "ASUS"},
				{Model: "VivoBook S15", ModelType: "VivoBookS15", Board: "ASUS"},
				{Model: "VivoBook S15 X513", ModelType: "VivoBookS15X513", Board: "ASUS"},
				{Model: "VivoBook Pro 14", ModelType: "VivoBookPro14", Board: "ASUS"},
				{Model: "VivoBook Pro 14 K3400", ModelType: "VivoBookPro14K3400", Board: "ASUS"},
				{Model: "VivoBook Pro 15", ModelType: "VivoBookPro15", Board: "ASUS"},
				{Model: "VivoBook Pro 15 K3500", ModelType: "VivoBookPro15K3500", Board: "ASUS"},
				{Model: "VivoBook Flip 14", ModelType: "VivoBookFlip14", Board: "ASUS"},
				{Model: "VivoBook Flip 15", ModelType: "VivoBookFlip15", Board: "ASUS"},
				// ROG 系列（游戏）
				{Model: "ROG Zephyrus G14", ModelType: "ROGZephyrusG14", Board: "ASUS"},
				{Model: "ROG Zephyrus G14 GA402", ModelType: "ROGZephyrusG14GA402", Board: "ASUS"},
				{Model: "ROG Zephyrus G15", ModelType: "ROGZephyrusG15", Board: "ASUS"},
				{Model: "ROG Zephyrus G15 GA503", ModelType: "ROGZephyrusG15GA503", Board: "ASUS"},
				{Model: "ROG Zephyrus G16", ModelType: "ROGZephyrusG16", Board: "ASUS"},
				{Model: "ROG Zephyrus G16 GU605", ModelType: "ROGZephyrusG16GU605", Board: "ASUS"},
				{Model: "ROG Strix G15", ModelType: "ROGStrixG15", Board: "ASUS"},
				{Model: "ROG Strix G15 G513", ModelType: "ROGStrixG15G513", Board: "ASUS"},
				{Model: "ROG Strix G16", ModelType: "ROGStrixG16", Board: "ASUS"},
				{Model: "ROG Strix G16 G614", ModelType: "ROGStrixG16G614", Board: "ASUS"},
				{Model: "ROG Strix G17", ModelType: "ROGStrixG17", Board: "ASUS"},
				{Model: "ROG Strix G18", ModelType: "ROGStrixG18", Board: "ASUS"},
				{Model: "ROG Flow X13", ModelType: "ROGFlowX13", Board: "ASUS"},
				{Model: "ROG Flow X16", ModelType: "ROGFlowX16", Board: "ASUS"},
				// TUF Gaming 系列（游戏）
				{Model: "TUF Gaming F15", ModelType: "TUFF15", Board: "ASUS"},
				{Model: "TUF Gaming F15 FX506", ModelType: "TUFF15FX506", Board: "ASUS"},
				{Model: "TUF Gaming F17", ModelType: "TUFF17", Board: "ASUS"},
				{Model: "TUF Gaming A15", ModelType: "TUFA15", Board: "ASUS"},
				{Model: "TUF Gaming A15 FA506", ModelType: "TUFA15FA506", Board: "ASUS"},
				{Model: "TUF Gaming A16", ModelType: "TUFA16", Board: "ASUS"},
				{Model: "TUF Gaming A17", ModelType: "TUFA17", Board: "ASUS"},
				// ExpertBook 系列（商务）
				{Model: "ExpertBook B9", ModelType: "ExpertBookB9", Board: "ASUS"},
				{Model: "ExpertBook B9 B9400", ModelType: "ExpertBookB9B9400", Board: "ASUS"},
				{Model: "ExpertBook B5", ModelType: "ExpertBookB5", Board: "ASUS"},
				{Model: "ExpertBook B5 B5500", ModelType: "ExpertBookB5B5500", Board: "ASUS"},
				{Model: "ExpertBook P2", ModelType: "ExpertBookP2", Board: "ASUS"},
				{Model: "ExpertBook P5", ModelType: "ExpertBookP5", Board: "ASUS"},
			},
			"Samsung": {
				// Galaxy Book 系列（印度市场）
				{Model: "Galaxy Book Pro", ModelType: "GalaxyBookPro", Board: "Samsung"},
				{Model: "Galaxy Book Pro 360", ModelType: "GalaxyBookPro360", Board: "Samsung"},
				{Model: "Galaxy Book2 Pro", ModelType: "GalaxyBook2Pro", Board: "Samsung"},
				{Model: "Galaxy Book2 Pro 360", ModelType: "GalaxyBook2Pro360", Board: "Samsung"},
				{Model: "Galaxy Book3 Pro", ModelType: "GalaxyBook3Pro", Board: "Samsung"},
				{Model: "Galaxy Book3 Pro 360", ModelType: "GalaxyBook3Pro360", Board: "Samsung"},
				{Model: "Galaxy Book4 Pro", ModelType: "GalaxyBook4Pro", Board: "Samsung"},
				{Model: "Galaxy Book4 Pro 360", ModelType: "GalaxyBook4Pro360", Board: "Samsung"},
				{Model: "Galaxy Book Go", ModelType: "GalaxyBookGo", Board: "Samsung"},
				{Model: "Galaxy Book2 Go", ModelType: "GalaxyBook2Go", Board: "Samsung"},
				{Model: "Galaxy Book Flex", ModelType: "GalaxyBookFlex", Board: "Samsung"},
				{Model: "Galaxy Book Flex2", ModelType: "GalaxyBookFlex2", Board: "Samsung"},
				{Model: "Galaxy Book Odyssey", ModelType: "GalaxyBookOdyssey", Board: "Samsung"},
			},
			"LG": {
				// Gram 系列（超轻薄，印度市场）
				{Model: "LG Gram 14", ModelType: "LGGram14", Board: "LG"},
				{Model: "LG Gram 15", ModelType: "LGGram15", Board: "LG"},
				{Model: "LG Gram 16", ModelType: "LGGram16", Board: "LG"},
				{Model: "LG Gram 17", ModelType: "LGGram17", Board: "LG"},
				{Model: "LG Gram 2-in-1 14", ModelType: "LGGram2in114", Board: "LG"},
				{Model: "LG Gram 2-in-1 16", ModelType: "LGGram2in116", Board: "LG"},
			},
			"Toshiba": {
				// Dynabook 系列（原Toshiba，印度市场）
				{Model: "Dynabook Portege X30", ModelType: "DynabookPortegeX30", Board: "Toshiba"},
				{Model: "Dynabook Portege X40", ModelType: "DynabookPortegeX40", Board: "Toshiba"},
				{Model: "Dynabook Tecra X40", ModelType: "DynabookTecraX40", Board: "Toshiba"},
				{Model: "Dynabook Tecra X50", ModelType: "DynabookTecraX50", Board: "Toshiba"},
				{Model: "Dynabook Satellite Pro", ModelType: "DynabookSatellitePro", Board: "Toshiba"},
			},
			"Fujitsu": {
				// LifeBook 系列（商务，印度市场）
				{Model: "LifeBook U7411", ModelType: "LifeBookU7411", Board: "Fujitsu"},
				{Model: "LifeBook U7511", ModelType: "LifeBookU7511", Board: "Fujitsu"},
				{Model: "LifeBook U7311", ModelType: "LifeBookU7311", Board: "Fujitsu"},
			},
		},
	}

	_ = fingerprint.RegisterRegion(config)
}
